### ISSUE TITLE
Bill should return line items, not entire objects

### ISSUE THREAD

**Issue by jbytes1027** [evan-scales/PalmetoProgrammers547#33]

**Comment by epadams** [comment]
What do you mean by this? And how is it supposed differ from `GetTotals`?

**Comment by jbytes1027** [comment]
Instead of returning `items` with item objects, return a list of cost description pairs.  (surcharges) like tax and bundle surcharges.

Aka this is how the tax surcharges are returned. Return a list like this for the item costs too.
```
    "taxSurcharges": [
        {
            "cost": 0.0,
            "description": "Sales Tax"
        }
    ]
```
