### ISSUE TITLE
Add DbSet for new models

### ISSUE THREAD

**Issue by evan-scales** [evan-scales/PalmetoProgrammers547#7]
![image](https://github.com/evan-scales/PalmetoProgrammers547/assets/70162138/c86ad394-1448-4693-8faf-fec79c445031)
Error getting products because no DbSet

AC
- [x] Add DbSet for new models

See [here](https://github.com/evan-scales/PalmetoProgrammers547/blob/main/ShopAPI/ShopAPI/Data/ApplicationDbContext.cs#L52)

**Comment by epadams** [comment]
Done, #8 for review

**Comment by evan-scales** [comment]
merged
